[package]
name = "simple_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
robcore = { path = "../robcore/" }
eframe = { version = "0.30.0" }
clap = { version = "4.5.28", features = ["derive"] }
