[patch.crates-io.nav2_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/nav2_msgs/share/nav2_msgs/rust"

[patch.crates-io.nav_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/nav_msgs/share/nav_msgs/rust"

[patch.crates-io.geographic_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/geographic_msgs/share/geographic_msgs/rust"

[patch.crates-io.rclrs]
path = "/home/balling/projects/RIC/ros_ws/install/rclrs/share/rclrs/rust"

[patch.crates-io.geometry_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/geometry_msgs/share/geometry_msgs/rust"

[patch.crates-io.test_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/test_msgs/share/test_msgs/rust"

[patch.crates-io.std_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/std_msgs/share/std_msgs/rust"

[patch.crates-io.rosgraph_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/rosgraph_msgs/share/rosgraph_msgs/rust"

[patch.crates-io.rcl_interfaces]
path = "/home/balling/projects/RIC/ros_ws/install/rcl_interfaces/share/rcl_interfaces/rust"

[patch.crates-io.action_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/action_msgs/share/action_msgs/rust"

[patch.crates-io.service_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/service_msgs/share/service_msgs/rust"

[patch.crates-io.unique_identifier_msgs]
path = "/home/balling/projects/RIC/ros_ws/install/unique_identifier_msgs/share/unique_identifier_msgs/rust"

[patch.crates-io.builtin_interfaces]
path = "/home/balling/projects/RIC/ros_ws/install/builtin_interfaces/share/builtin_interfaces/rust"

[patch.crates-io.rosidl_runtime_rs]
path = "/home/balling/projects/RIC/ros_ws/install/rosidl_runtime_rs/share/rosidl_runtime_rs/rust"
