[package]
name = "robcore"
version = "0.1.0"
edition = "2021"

[features]
default = []
cli = ["clap"]

[dependencies]
emath = { version = "0.30.0", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive"]}
clap = { version = "4.5.31", features = ["derive"], optional = true }
