#!/usr/bin/env bash

function check_uncommitted_changes() {
    if ! git diff-index --quiet HEAD --; then
        echo "You have uncommitted changes. Please commit or stash them before pushing."
        exit 1
    fi
}

function lint()
{
    cargo clippy --manifest-path "$1/Cargo.toml" -- -D warnings
    if [ $? -ne 0 ]; then
        echo -e "\nPlease fix the clippy warnings in '$1'."
        exit 1
    fi
}

# Fail early if uncommitted changes
check_uncommitted_changes

lint botbrain
lint simple_sim
lint trainer

# Clippy can change lock files
check_uncommitted_changes 
