#!/usr/bin/env bash

function check_format()
{
    cargo fmt --manifest-path "$1/Cargo.toml" -- --check
    if [ $? -ne 0 ]; then
        echo -e "\nPlease format your files in '$1'."
        exit 1
    fi
}

check_format botbrain
check_format simple_sim
check_format trainer
