#!/usr/bin/env bash

function lint()
{
    cargo clippy --manifest-path "$1/Cargo.toml" -- -D warnings
    if [ $? -ne 0 ]; then
        echo -e "\nPlease fix the clippy warnings in '$1'."
        exit 1
    fi
}

lint robcore
lint simple_sim
