[package]
name = "trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
botbrain = { path = "../botbrain" }
ringbuffer = "0.15.0"
simple_sim = { path = "../simple_sim", features = ["single-thread"] }
