name: Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - report/**
      - botbrain/**
      - simple_sim/**

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v31

      - name: Generate Site
        run: nix build .#site

      - name: Upload Documentation Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

  # Deploy job
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
